# Generated by Django 4.1.6 on 2023-02-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bio',
            new_name='body',
        ),
    ]
